import Providers from "./providers";
import { Lexend_Deca, Inter } from "next/font/google";
import "./globals.css";

const lexendDeca = Lexend_Deca({ subsets: ["latin"] });
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lexendDeca.className} ${inter.className}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
